### ISSUE TITLE
java.lang.UnsatisfiedLinkError: net.sf.jni4net.Bridge.initDotNet()I

### ISSUE THREAD

**Issue by leonardolr** [jni4net/jni4net#14]
Hello All! 

I've found this library and I loved it so much... But I can't start using it... I don't know what I'm doing wrong, but can anyone help me?

I've read the wiki and environment setup. And I'm trying to do a simple hello world in Java calling C#.

But I'm receiving this error:
java.lang.UnsatisfiedLinkError: net.sf.jni4net.Bridge.initDotNet()I

Here's my Folder setup in Eclipse:
![captura de tela 2015-06-19 as 21 51 53](https://cloud.githubusercontent.com/assets/6147142/8265327/e2419670-16cd-11e5-85bd-dae9ea275186.png)

Here's my Main Class:
```
package testJni4net;

import java.io.IOException;
import java.lang.String;

import net.sf.jni4net.Bridge;
import system.*;
import system.Object;
import system.io.TextWriter;
import system.collections.IDictionary;
import system.collections.IEnumerator;

public class Teste1 {
	public static void main(String[] args) throws IOException {
		// create bridge, with default setup
		// it will lookup jni4net.n.dll next to jni4net.j.jar
		Bridge.setVerbose(true);

		Bridge.init();

		// here you go!
		Console.WriteLine("Hello .NET world!\n");

		// OK, simple hello is boring, let's play with System.Environment
		// they are Hashtable realy
		final IDictionary variables = system.Environment
				.GetEnvironmentVariables();

		// let's enumerate all keys
		final IEnumerator keys = variables.getKeys().GetEnumerator();
		while (keys.MoveNext()) {
			// there hash table is not generic and returns system.Object
			// but we know is should be system.String, so we could cast
			final system.String key = (system.String) keys.getCurrent();
			Console.Write(key);

			// this is automatic conversion of JVM string to system.String
			Console.Write(" : ");

			// we use the hashtable
			Object value = variables.getItem(key);

			// and this is JVM toString() redirected to CLR ToString() method
			String valueToString = value.toString();
			Console.WriteLine(valueToString);
		}

		// Console output is really TextWriter on stream
		final TextWriter writer = Console.getOut();
		writer.Flush();
	}
}
```

And here's the full stack trace:
```
Can't initialize jni4net Bridgenet.sf.jni4net.Bridge.initDotNet()I
Exception in thread "main" net.sf.jni4net.inj.INJException: Can't initialize jni4net Bridge
	at net.sf.jni4net.CLRLoader.init(CLRLoader.java:45)
	at net.sf.jni4net.Bridge.init(Bridge.java:35)
	at net.sf.jni4net.Bridge.init(Bridge.java:31)
	at testJni4net.Teste1.main(Teste1.java:19)
Caused by: java.lang.UnsatisfiedLinkError: net.sf.jni4net.Bridge.initDotNet()I
	at net.sf.jni4net.Bridge.initDotNet(Native Method)
	at net.sf.jni4net.CLRLoader.init(CLRLoader.java:37)
	... 3 more
```

Please, can anyone help me?

Thanks!

**Comment by pavelsavara** [comment]
https://www.chilkatsoft.com/java-loadLibrary-Windows.asp

**Comment by leonardolr** [comment]
Hey pavel, thanks for your fast answer. But I solved this issue downgrading the version jni4net 0.8.8 version to 0.8.3 version. And now it's working like a charm. I don't know details of the error, but my environment is Windows XP - jdk7.

**Comment by pavelsavara** [comment]
@leonardolr this is interesting, perhaps i made some new bugs between 0.8.3 and 0.8.8. What is the full path of deployment folder where the DLLs reside ?

**Comment by Ryan-Armstrong** [comment]
Hi
I ran into this issue of UnsatisfiedLinkError when trying to call a dll from a jar.
The cause in my case was the types of compilation and framework across c# and java - specifically that if the c# is built as 64bit, it needs the java to be 64bit built AND executed.
In my case, the tool I was using was running a 32bit jre but the proxygen and java compiler were 64bit.
In addition:
The .jar files taken from the jni4net/lib folder may need to be unblocked - this is at the file system level on Windows - in the Properties dialog from the file there is a button on the bottom right "Unblock" which appears if the file is blocked.
If it is there, click it to unblock the dll.
At the top level, the error is unsatisfied link - If in doubt, put the classpath, jvm settings and execute command line in a batch file and execute it from the command prompt.

**Comment by paul-peters** [comment]
Just to put my two cents in: 
I got 
`Exception in thread "main" java.lang.UnsatisfiedLinkError: mycsharpdemocalc.DemoCalc.__ctorDemoCalc0(Lnet/sf/jni4net/inj/IClrProxy;)V`
in the myCSharpDemoCalc sample in version 0.8.8. 

The last step to solve the issue was to add `System.load` at the beginning of `MyCalcUsageInJava` for `jni4net.n.w64.v40-0.8.8.0.dll`.

I also did the following, but I do not know whether it is needed:
1. deinstalled f-secure
2. Ryan-Armstrong
>  The .jar files taken from the jni4net/lib folder may need to be unblocked - this is at the file system level on Windows - in the Properties dialog from the file there is a button on the bottom right "Unblock" which appears if the file is blocked.
For ne aksi the proxygen.exe was blocked (but could be executed)

**Comment by denis111** [comment]
I have the same UnsatisfiedLinkError error and nothing helps: tried versions 0.8.7, 0.8.6, 0.8.3 and tried to put System.load and unblock files in explorer without any success. The same result everytime, no solution works... (jdk8, 64bit, win10)

**Comment by paul-peters** [comment]
@denis111 
I finally loaded 4 dlls:

jni4net.n.w64.v40-0.8.8.0
jni4net.n-0.8.8.0
MyCSharpDemoCalc.j4n
MyCSharpDemoCalc

I had a look into the dlls with "dependency walker" to figure out the dependencies

Keep on trying. It is really worth it. After solving the linking problem I wrote my own ant build and now its really seemless: do some C# Programming in Visual Studio, build, refresh Eclipse and go on using the generated Java API. It really works like a charm.

**Comment by denis111** [comment]
I don't try it with MyCSharpDemoCalc but with our client's private library written in .net and it always produces this error on calling the constructor of the class inside this library (new ).
For now we ended up writing small console app in .net calling this library and just execute this app from java...

**Comment by luigiw** [comment]
I had the same UnsatifiedLinkError running mycsharpdemocalc sample in 0.8.8.0 jni4net package. Two things solved my problem.

1. Dll given in mycsharpdemocalc is compiled with 64bit .net framework, you'll need 64 bit JDK to execute run.cmd.
2. In my case I was also confused between original dll file, which is called MyCSharpDemoCalc.dll, and the newly generated dll, which is called, MyCSharpDemoCalc.j4n.dll, noticed generated one has .j4n in its name. What gets loaded in java code is the generated dll, but the original dll needs to be present in the same folder(classpath) as well.

I also used ILSpy (http://ilspy.net/) to check weather a dll is built with 64 bit or 32 bit, and content of the dll. I was very frustrated debugging the issue, hopefully my two cents can help somebody.

**Comment by saffaura** [comment]
I get this exception when running my code from a subfolder with a space in the name. For example "A Test" will give me the UnsatifiedLinkError, but A_Test works just fine.

**Comment by shrinidhin** [comment]
Hi! I have the same issue right now. I have tried solutions stated above and none of the seem to work. I have mentioned my problem in detail in the post below : 
https://stackoverflow.com/questions/49726372/need-to-reference-and-use-a-c-sharp-dll-in-java
I have been breaking my head over this for quite sometime. I would be relieved if anyone has a solution for this!

**Comment by WahidNasri** [comment]
@shrinidhin 
I have the same problem and I am using Eclipse as IDE. The solution is to copy all the dll and jar files in the root directory of your java project ( jni4net.j-0.8.8.0.jar and the other dlls, your .Net project DLL, the generated .j4n.jar file). And from Eclipse, you add jni4net.j-0.8.8.0.jar to buil path by right-click on it --> build Path --> Add to build path, do the same for the generated .j4n.jar file). this should work for you too.

And check this if you want: https://www.youtube.com/watch?time_continue=351&v=8OoSK_RWUe4

Regards

**Comment by shrinidhin** [comment]
@WahidNasri Thank you so much for your reply.I have followed the exact steps mentioned in the dll,I have already added my Jni.net jar files within the project folder directory.And added them to the build path
But the issue still persists.Could you tell me what I am missing here?

**Comment by shrinidhin** [comment]
@WahidNasri Slight correction.I have followed the steps mentioned in the video.

**Comment by WahidNasri** [comment]
@shrinidhin 
I faced that too, In the implementation of Bridge.init(), it searches the source directory of "jni4net.j-0.8.8.0.jar" to find and load "jni4net.n.[platform].dll".

Like the most of cases, the  "_.j4n.dll" is in the output directory, but "jni4net.n.[platform].dll" is loaded from your source directory.
I solved this by passing in the output directory (as a File) into Bridge.init(), so that it searches and loads from that directory instead of the source directory.
For my case, I used:

`Bridge.setVerbose(false);`
`Bridge.init(new File(System.getProperty("user.dir")));`
`Bridge.LoadAndRegisterAssemblyFrom(new File("xxxx.j4n.dll"));`
 And it worked very well

**Comment by shrinidhin** [comment]
@WahidNasri Thank you so much for your reply. This is my code : 
public static void main(String[] args) throws IOException {
	Bridge.setVerbose(true);
        Bridge.init(new File(System.getProperty("C:\\Users\\Shrinidhi Narasimhan\\eclipseworkspace\\OrionCom\\jni4net.n.w64.v40-0.8.3.0.dll")));
        File proxyAssemblyFile=new File("OrionForPython.dll");
        Bridge.LoadAndRegisterAssemblyFrom(proxyAssemblyFile);
        DynamicOrion orion=new DynamicOrion();
    	orion.ReqLogin("user", "abc@123", "");
        System.out.print(res);


System.getProperty("C:\\Users\\Shrinidhi Narasimhan\\eclipse-workspace\\OrionCom\\jni4net.n.w64.v40-0.8.3.0.dll 
This is the path to my eclipse project,where my dlls are.

OrionForPython.dll
This is the name of the dll i need to reference,present in the same path. Also tried using "OrionForPython.j4n.dll" here.
I am getting Null pointer Exception
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at OrionComClass.main(OrionComClass.java:9)

**Comment by rfabrizio91** [comment]
I was struggling with the same issue, but I applied the solution provided by @WahidNasri. In my case, I was trying to create an executable jar file using javafx-maven-plugin, but there are a few behaviors that cause errors on finding and linking my external libraries. So I tried with the export option from Eclipse, but had the same errors. 

After investigating a lot, I found that we can include all libraries in a separate folder from runnable jar just clicking on "Copy required libraries..". Then I did what WahidNasri mentioned, finally adding manually the jars and dlls created with proxygen, and now all works perfectly.

![image](https://user-images.githubusercontent.com/13683136/39226427-0f568836-4818-11e8-9b1f-9502c40f194f.png)

![image](https://user-images.githubusercontent.com/13683136/39226486-6ebaadc0-4818-11e8-8c8a-7897e7c88669.png)
