### ISSUE TITLE
proxygen fails

### ISSUE THREAD

**Issue by NathanSweet** [jni4net/jni4net#16]
This DLL fails when running `proxygen.exe`:
http://esotericsoftware.com/temp/test.dll

Error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at net.sf.jni4net.proxygen.model.GType.UpdateNames()
   at net.sf.jni4net.proxygen.model.Repository.Analyze()
   at net.sf.jni4net.proxygen.Program.Work(String[] args)
   at net.sf.jni4net.proxygen.Program.Main(String[] args)
```

The DLL provided above is 64-bit, though I tried a 32-bit version and it failed in the same way.

Any ideas about a fix or what might be going wrong? Note I unfortunately don't have access to the DLL source code.

**Comment by NathanSweet** [comment]
Sorry, more digging seems that generics are not supported, which would make this a duplicate of #4.
