### ISSUE TITLE
java.lang.UnsatisfiedLinkError: package.Wrapper.__ctorWrapper0(Lnet/sf/jni4net/inj/IClrProxy;)V  with 0.8.8 only

### ISSUE THREAD

**Issue by Berndq** [jni4net/jni4net#25]
I have a working project with 0.8.6, calling dotnet code from java. I wanted to upgrade to 0.8.8 to have the MIT instead of the LGPL license. Unfortunately my project does not work with 0.8.8. I can compile the proxies but at runtime I get:

loading core from C:/.../work/jni4net/.../jni4net.n-0.8.8.0.dll
loading jni4net.n-0.8.8.0, Version=0.8.8.0, Culture=neutral, PublicKeyToken=134a23405600bab4 from C:\...\work\jni4net\...\jni4net.n-0.8.8.0.dll
loaded jni4net.n-0.8.8.0, Version=0.8.8.0, Culture=neutral, PublicKeyToken=134a23405600bab4 from C:\...\work\jni4net\...\jni4net.n-0.8.8.0.dll
Initialized jni4net core
core loaded from C:/.../work/jni4net/.../jni4net.n-0.8.8.0.dll
clr.version         :v4.0.30319
clr.arch            :32bit
java.home           :C:\Program Files (x86)\Java\jdk1.7.0_11\jre
java.version        :1.7.0_11
sun.arch.data.model :32
loading ...JavaWrapper.j4n, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from C:\...\work\jni4net\...\...JavaWrapper.j4n.dll
loaded ...JavaWrapper.j4n, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from C:\...\work\jni4net\...\...JavaWrapper.j4n.dll
Exception in thread "main" java.lang.UnsatisfiedLinkError: package.Wrapper.__ctorWrapper0(Lnet/sf/jni4net/inj/IClrProxy;)V
	at ....Wrapper.__ctorWrapper0(Native Method)
	at ....Wrapper.<init>(Wrapper.java:25)
	at ...Impl.<init>(...Impl.java:29)
	at ....Test.main(Test.java:92)
Java Result: 1

Reverting back to 0.8.6 makes the project work again.

**Comment by Berndq** [comment]
Maybe this is related to or a duplicate of of https://github.com/jni4net/jni4net/issues/14
