### ISSUE TITLE
Proxygen fails to produce proxies on Mixed Mode Assembly

### ISSUE THREAD

**Issue by kyle-oshaughnessy** [jni4net/jni4net#40]
Hi,

I'm trying to use a C# .NET dll that was built by a 3rd party software company. I don't know what version of .NET the dll was built agaist but I know that it's v3.5 or earlier, so it was built against CLR 2.0. The issue I'm having is that proxygen.exe fails to run on the dll giving the error "Mixed Mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration". I know that this is a common issue that people using jni4net encounter when trying to encorporate their proxies into their java projects, but I can't find any reports of proxygen failing to build the proxies due to this. 

I already successfully built and used the proxies for some simple test C# .NET dlls that I built against .NET v3.5 and even against .NET v2.0 (Both of which use CLR 2.0), but this 3rd party dll just keeps failing.

proxygen.exe.config is already configured with for both versions (see below) so I'm not sure what I can do differently.
![image](https://cloud.githubusercontent.com/assets/15810643/18761163/da3acef0-80d1-11e6-8850-f0f13bbc3a42.png)

Any idea what I could do to solve this?

Thanks

**Comment by kyle-oshaughnessy** [comment]
I was just looking at the error message and saw note of assemblySecurity. This made me wonder if the 3rd party somehow added security settings to ensure that the dll can't be built into a proxy. If that's the case, how can I run the dll code from Java?

This is the Error I get: 

System.IO.FileLoadException: Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional
 configuration information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& s
tackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm,
Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at net.sf.jni4net.proxygen.model.Repository.LoadFile(String file)
   at net.sf.jni4net.proxygen.model.Repository.LoadAssemblies()
   at net.sf.jni4net.proxygen.model.Repository.Register()
   at net.sf.jni4net.proxygen.Program.Work(String[] args)
   at net.sf.jni4net.proxygen.Program.Main(String[] args)

**Comment by kyle-oshaughnessy** [comment]
I tried adding "useLegacyV2RuntimeActivationPolicy="true"" to the startup line and I get this error instead: 

System.NullReferenceException: Object reference not set to an instance of an object.
   at net.sf.jni4net.proxygen.model.Repository.RegisterCLRCall(GType type, MethodBase method)
   at net.sf.jni4net.proxygen.model.Repository.RegisterCLRMethod(GType type, MethodInfo method, Boolean register)
   at net.sf.jni4net.proxygen.model.Repository.RegisterCLRMethods(GType type, Boolean register)
   at net.sf.jni4net.proxygen.model.Repository.PreLoadMethods(GType type)
   at net.sf.jni4net.proxygen.model.Repository.Analyze()
   at net.sf.jni4net.proxygen.Program.Work(String[] args)
   at net.sf.jni4net.proxygen.Program.Main(String[] args)

**Comment by kyle-oshaughnessy** [comment]
All Good I got it to work!

**Comment by KittenAvenger** [comment]
How did you solve the last error with System.NullReferenceException?

**Comment by kyle-oshaughnessy** [comment]
@KittenAvenger For me I think the issue ended up being the version of jni4net.n.wXX.vXX-0.8.3.0.dll I was using. Make sure that you are using w32/w64 for 32/64 bit OS respectively, and make sure that you are using v20/v30 for CLR 2.0/3.0 builds respectively. That may not have been the solution to this specific error but it was definitely the main solution to all the problems I was having.
