### ISSUE TITLE
Cannot create proxy

### ISSUE THREAD

**Issue by Tobisaninfo** [jni4net/jni4net#42]
While I'll try to create the clr and jvm files using the proxygen tool, it fails with a NullReferenceException. The dll I use was the NAudio.dll.

Here is the Error message:
...\jni4net-0.8.8.0-bin\bin>proxygen.exe \NAudioNative\NAudio.dll -wd \NAudioNative
jni4net.proxygen - Copyright (C) 2009 Pavel Savara - licensed under GPLv3

System.NullReferenceException: Object reference not set to an instance of an object.
   at net.sf.jni4net.proxygen.model.Repository.RegisterCLRCall(GType type, MethodBase method)
   at net.sf.jni4net.proxygen.model.Repository.RegisterCLRMethod(GType type, MethodInfo method, Boolean register)
   at net.sf.jni4net.proxygen.model.Repository.RegisterCLRMethods(GType type, Boolean register)
   at net.sf.jni4net.proxygen.model.Repository.PreLoadMethods(GType type)
   at net.sf.jni4net.proxygen.model.Repository.Analyze()
   at net.sf.jni4net.proxygen.Program.Work(String[] args)
   at net.sf.jni4net.proxygen.Program.Main(String[] args)

**Comment by sibiarunachalam** [comment]
I encountered the same problem.
Have you resolved it?

**Comment by Tobisaninfo** [comment]
No I haven't resolve this problem. I have simple written a wrapper library in C#, that uses NAudio.

**Comment by sibiarunachalam** [comment]
#16  Generics are not supported.
