### ISSUE TITLE
proxygen.exe cannot load jvm.dll?

### ISSUE THREAD

**Issue by Alban34** [jni4net/jni4net#43]
Hi,
I setup the JAVA_HOME to my JDK (1.8.0_121 - 32bits) and proxygen keeps telling me that it cannot load the jvm.dll:

`System.DllNotFoundException: Unable to load DLL 'jvm.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at net.sf.jni4net.jni.JNI.Dll.JNI_GetDefaultJavaVMInitArgs(JavaVMInitArgs* args)
   at net.sf.jni4net.jni.JNI.Init()
   at net.sf.jni4net.jni.JNI.CreateJavaVM(JavaVM& jvm, JNIEnv& env, Boolean attachIfExists, String[] options)
   at net.sf.jni4net.Bridge.CreateJVM()
   at net.sf.jni4net.Bridge.CreateJVM(BridgeSetup setup)
   at net.sf.jni4net.proxygen.model.Repository.LoadClasspath()
   at net.sf.jni4net.proxygen.model.Repository.Register()
   at net.sf.jni4net.proxygen.Program.Work(String[] args)
   at net.sf.jni4net.proxygen.Program.Main(String[] args)`

I cannot find any recommendation or configuration regarding this JVM path.

My command line is 
`proxygen myDll.dll -wd ./proxygen`

My dll is compiled in 32bits mode.

I am using Windows 10 64bits.

Am I missing something?

Thanks.

**Comment by Alban34** [comment]
I finally found out the issue: I was missing my %JAVA_HOME%\bin in my Windows PATH
