### ISSUE TITLE
calling java from c# Loader sun.misc.Launcher$AppClassLoader@ error

### ISSUE THREAD

**Issue by hezite** [jni4net/jni4net#47]
i built a very small and simple helloWorld program in java (has interface and in class has system.lang.out.println("hello world"))). i wrapped it with proxy gen. now that i'm trying to attach it to c# (going by meCalc example) i get the following error:

Unhandled Exception: net.sf.jni4net.jni.JNIException: Can't load java class for dt09120958.HelloWorld09120958 from classLoader sun.misc.Launcher$AppClassLoader@c387f44 ---> java.lang.ClassNotFoundException: dt09120958.HelloWorld09120958
   at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
   at net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
   at java.lang.ClassLoader.loadClass(String par0)
   at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   --- End of inner exception stack trace ---
   at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
   at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
   at netdt09120958.Program.Main(String[] args)

my c# code:
```
static void Main(string[] args)
        {
            var bridgeSetup = new BridgeSetup();
            bridgeSetup.AddAllJarsClassPath(".");
            Bridge.CreateJVM(bridgeSetup);
            Bridge.RegisterAssembly(typeof(HelloWorld09120958).Assembly);

            IHelloWorld09120958 calc = new HelloWorld09120958();
            calc.SayHello();
            Console.ReadKey();
        }
```

why is that so? what am i doing wrong and how can i fix it to work?

**Comment by hezite** [comment]
found my answer: package in java can't have any uppercase letters!
