### ISSUE TITLE
Can't load java class.

### ISSUE THREAD

**Issue by Fehrox** [jni4net/jni4net#48]
Following the instructions from the wiki, everything works until the code is run.

Here's the Java:
```
    package robotbridge;
    import java.awt.AWTException;
    import java.awt.Robot;

    public class RobotBridge {
	
	    Robot robot = new Robot();
	
	    public RobotBridge() throws AWTException {}
	
	    public void MoveMouse(int x, int z) {
	    	robot.mouseMove(x, z);
	    }
	
	    public void Click() {
	    	robot.mousePress(0);
	    }
	
    }
```

And the C#:
```
   using net.sf.jni4net;
   using robotbridge;

   class JavaRobotInput {

        public static void MoveMouse(int x, int y) {
            var setup = new BridgeSetup();
            setup.Verbose = true;
            setup.AddAllJarsClassPath("./");

            Bridge.CreateJVM(setup);
            Bridge.RegisterAssembly(typeof(RobotBridge).Assembly);

            RobotBridge robotInput = new RobotBridge();
            robotInput.MoveMouse(x, y);
        }
    }
```

This results in the following C# run-time exception:

> Can't load java class for robotbridge.RobotBridge from classLoader sun.misc.Launcher$AppClassLoader@387f44
>    at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
   at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
   at Filirs.Utilities.JavaRobotInput.MoveMouse(Int32 x, Int32 y) in JavaRobotInput.cs:line 14
   at Filirs.StateMachine.Test() in StateMachine.cs:line 46
   at Filirs.Program.Main(String[] args) in Program.cs:line 20

I may be missing something obvious here, but if so I can't see it and I've been looking for a while. Any help is much appreciated.

**Comment by starryfei** [comment]
@Fehrox I have the same problem, have you solved it?

**Comment by Fehrox** [comment]
@starryfei No, I never did. Would up using a different solution altogether.

**Comment by starryfei** [comment]
@Fehrox Can you tell me your solution? Thank you

**Comment by Fehrox** [comment]
http://www.botsuite.net/
