### ISSUE TITLE
Proxygen fail

### ISSUE THREAD

**Issue by francogp** [jni4net/jni4net#54]
when I execute proxygen.exe I get this error;

`jni4net.proxygen - Copyright (C) 2009 Pavel Savara - licensed under GPLv3

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at net.sf.jni4net.proxygen.model.GType.UpdateNames()
   at net.sf.jni4net.proxygen.model.Repository.Analyze()
   at net.sf.jni4net.proxygen.Program.Work(String[] args)
   at net.sf.jni4net.proxygen.Program.Main(String[] args)`

**Comment by jsyzthz** [comment]
any update? same error.
