### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an obj ect.

### ISSUE THREAD

**Issue by suryamNaidu** [jni4net/jni4net#59]
C:\Users\st6\Desktop\JNI-Build\bin>.\proxygen.exe "D:\processing-engine\ImpactOV
T\OVT\bin\Release\OVT.dll" -wd "C:\Users\st6\Desktop\JNI-Build"
jni4net.proxygen - Copyright (C) 2009 Pavel Savara - licensed under GPLv3
Loaded D:\processing-engine\ImpactOVT\OVT\bin\Release\OVT.dll

System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at net.sf.jni4net.proxygen.model.GType.UpdateNames()
   at net.sf.jni4net.proxygen.model.Repository.Analyze()
   at net.sf.jni4net.proxygen.Program.Work(String[] args)
   at net.sf.jni4net.proxygen.Program.Main(String[] args)

**Comment by spacemonkey48** [comment]
I am running into this issue too.  I am wondering if this is because my .net dll is obfuscated.
