### ISSUE TITLE
Can't initialize proxy java.lang.System running Java 11

### ISSUE THREAD

**Issue by usboxes** [jni4net/jni4net#64]
The bridge fails to intialize trying to invoke reflective calls on the proxy java.lang.System when running with Java 11.

Apparently, a java.lang.LinkageError occurs do to a reflective method that has been removed from Java 11 ( System.runFinalizersOnExit() ) and is being invoked as part of Bridge.init(file). 

I am behind a firewall and am forced to use the existing binaries.  Is there a workaround for using the existing binaries or is a rebuild/recompile of Jni4net (using Java 11) the only possible solution?

Can't bind bridge:Can't initialize proxy java.lang.System
Can't bind bridge:net.sf.jni4net.jni.JNIException: Can't initialize proxy java.lang.System ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> java.lang.LinkageError: runFinalizersOnExit
   at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
   at net.sf.jni4net.jni.JNIEnv.GetStaticMethodID(Class clazz, String name, String sig)
   at java.lang.System.InitJNI(JNIEnv __env, Class __class)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at net.sf.jni4net.utils.Registry.RegisterStaticAndMethods(RegistryRecord record, JNIEnv env)
   --- End of inner exception stack trace ---
   at net.sf.jni4net.utils.Registry.RegisterStaticAndMethods(RegistryRecord record, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
   at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
   at net.sf.jni4net.Bridge.BindCore(JNIEnv env, BridgeSetup newSetup)
   at net.sf.jni4net.Bridge.initDotNetImpl(IntPtr envi, IntPtr clazz)
Can't initialize jni4net BridgeC
Exception in thread "AWT-EventQueue-0" net.sf.jni4net.inj.INJException: Can't initialize jni4net Bridge
	at net.sf.jni4net.CLRLoader.init(CLRLoader.java:45)

**Comment by pavelsavara** [comment]
Patch welcome

**Comment by aze-kool** [comment]
Hello,
we love the library and using it successfully with java 8.
 
with java 11, we are getting the same error. can you provide us a version 0.8.9. with the aboved mentioned patch.?
 we tried to build it ourselves but one of the Test gets failed. 
Any help will be really appreciated. 
```

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.sf.jni4net.test.TestClr
Can't initialize jni4net Bridgenet.sf.jni4net.Bridge.initDotNet()I
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.052 sec <<< FAILURE!
```
