### ISSUE TITLE
.Net Events on Java

### ISSUE THREAD

**Issue by Ripall** [jni4net/jni4net#67]
Hello,

I tried to use the .Net events as used in [this example](
https://github.com/jni4net/jni4net/blob/master/content/samples/winforms/java/TestForm.java) but I don't have access to `system.EventHandler`, I only can give a `system.MulticastDelegate` object.

I read that the proxygen should create the bridge. The only difference is that I am not using a event from the windows forms but generate it.

Does someone have an idea ?

Thanks.

**Comment by petkopetkovoms** [comment]
Hello,

I have the same problem.
Did you try to generate your own system.EventHandler?
In my case I get the code for the system.EventHandler from the example that you mentioned and renamed all match cases with AlertEventHandler. 
Also I copy and rename the EventHandler.generated.cs into AlertEventHandler.generated.cs and do the same thing with the code.
I edited the build.cmd and I put the AlertEventHandler.java for compilation and the new compiled classes in the jar file.
But I have new error:
 Can't initialize proxy PACKAGE.CLASS_NAME+AlertEventHandler ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> java.lang.LinkageError: Invoke
   at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
   at net.sf.jni4net.jni.JNIEnv.GetMethodID(Class clazz, String name, String sig)
   at PACKAGE.__AlertEventHandler.InitJNI(JNIEnv __env, Class __class)

Maybe my explanation will be helpful for solving the Ripall's problem.
If anybody have any suggestions please share it.

Thanks
