### ISSUE TITLE
jni4net with java 11 patch required new versin 0.8.9

### ISSUE THREAD

**Issue by aze-kool** [jni4net/jni4net#69]
Hello,
we love the library and using it successfully with java 8.

with java 11, we are getting the same error. can you provide us a version 0.8.9. with the aboved mentioned patch.? https://github.com/jni4net/jni4net/issues/64

we tried to build it ourselves but one of the Test gets failed.
Any help will be really appreciated.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.sf.jni4net.test.TestClr
Can't initialize jni4net Bridgenet.sf.jni4net.Bridge.initDotNet()I
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.052 sec <<< FAILURE!

**Comment by tothpe** [comment]
Hello,
we love the library too and using it successfully with java 7 and 8.
With java11, we have the same issue.

We tried also to build the newest master patch Version 0.8.9.0, but test gets failed too.
We need also help.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.sf.jni4net.test.TestClr
Can't initialize jni4net Bridgenet.sf.jni4net.Bridge.initDotNet()I
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.446 sec <<< FAILURE!

**Comment by aze-kool** [comment]
[binaries.zip](https://github.com/jni4net/jni4net/files/2818148/binaries.zip)
we have somehow managed to make build, that worked for us. no warranties though.

**Comment by tothpe** [comment]
Hi aze-kool,

thank you, but i cannot use ist without correct proxygen.exe.
Can you send me also the compiled proxygen.exe?

Best regards
Peter

Von: aze-kool [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. Januar 2019 17:32
An: jni4net/jni4net
Cc: TOTH Peter; Comment
Betreff: [NEWSLETTER] Re: [jni4net/jni4net] jni4net with java 11 patch required new versin 0.8.9 (#69)


binaries.zip<https://github.com/jni4net/jni4net/files/2818148/binaries.zip>
we have somehow managed to make build, that worked for us. no warranties though.

**Comment by mKay00** [comment]
I changed the proxygen.exe with a tool called dllrepl.exe which I found here:
https://stackoverflow.com/questions/3420008/hex-edit-a-dll-to-change-a-dependency-name

It seems to work for me
[proxygen_0.8.9.0.exe.zip](https://github.com/jni4net/jni4net/files/2837022/proxygen_0.8.9.0.exe.zip)

**Comment by aze-kool** [comment]
> Hi aze-kool, thank you, but i cannot use it without correct proxygen.exe. Can you send me also the compiled proxygen.exe and the dotnet 2.0 libraries? Best regards Peter

i have updated the comment

**Comment by tothpe** [comment]
Hi mKay00,
thank you very much, i can use the proxygen.exe and my JAR-files were created now successfully, 
but if i use it, then the following error occures:

Can't initialize jni4net Bridgenet.sf.jni4net.Bridge.initDotNet()I
Caused by: java.lang.UnsatisfiedLinkError: net.sf.jni4net.Bridge.initDotNet()I
        at net.sf.jni4net.Bridge.initDotNet(Native Method)
        at net.sf.jni4net.CLRLoader.init(CLRLoader.java:39)
        ... 10 more

i tested this with jre1.7.0_80 and jdk-11.0.2+9.

Can anybody help?

**Comment by tothpe** [comment]
Hi together,
Unfortunately I still can not use JNI4Net with Java 11.
I have tried to build the current version 0.8.8.0, but also without success. After adjusting the urls, as the repo has changed, it mostly ran but still ends up with an error similar to the 0.8.9.0.
Can someone help?
Attached the result console log of building.
[result.log](https://github.com/jni4net/jni4net/files/2859560/result.log)

**Comment by aze-kool** [comment]
you might need to adjust the path of sn.ex in visual studio. %ProgramFiles%\Microsoft SDKs\Windows\v7.0A\bin\sn.exe.

The error caused by: java.lang.UnsatisfiedLinkError: net.sf.jni4net.Bridge.initDotNet()I shows that your dll are not loaded in the program. 

	Bridge.setVerbose(true);
			Bridge.init();
			net.sf.jni4net.Bridge.LoadAndRegisterAssemblyFrom(new File(_J4N_DLL));
			net.sf.jni4net.Bridge.LoadAndRegisterAssemblyFrom(new File(YOUR_DLL));

**Comment by tothpe** [comment]
Thank you, i could now compile dotnet, but not java.
With your jar and my dotnet files i can generate my bridge and it runs with java 7 and java 11.

I expect, that when i compile the code without changes the runtime is MIT licensed.

@pavelsavara: When do you intend to publish the latest binaries?

[jni4net.zip](https://github.com/jni4net/jni4net/files/2888682/jni4net.zip)

**Comment by pavelsavara** [comment]
No, I didn't touch the code for years. I do not push binaries which I didn't build myself and I don't have environment setup to do the build at the moment. Sorry. 

At least people like you could help each other. It's open source after all :)
